version: '{branch}-{build}'
pull_requests:
  do_not_increment_build_number: true
install:
  - git submodule update --init --recursive
  - nuget restore
image: Visual Studio 2017
configuration: Release
platform: x64
cache:
  - '%LocalAppData%\NuGet\v3-cache' # NuGet v3
artifacts:
  - path: IPA/bin/$(configuration)
build:
  verbosity: normal
  project: BSIPA.sln
deploy:
- provider: GitHub
  release: BSIPA {NEWVER}
  auth_token:
    secure: KhF3q/zWEFwrW0QeZLqE3NAkWR4u9iVhsmcyzXvwwJ28fUy+MzW4CWBx3RxNM60t
  artifact: IPA\Bin\Release.zip
  draft: true
  force_update: true
  on:
    branch: master