version: 'BSIPA-{branch}-{build}'
environment:
  bsipa_version: '3.12.21'
  gh_acct_user:
    secure: Q4+sZFxDOY7dL9prok446NlMzp3orJA0YmiBz9AYWLs=
  gh_acct_pw:
    secure: Aqn8uiVQ4vvjwgUYUaO4iGWJwqDVQppkYWU2x6s/p4ZgRrhI28FiIcFv6/wqxS9n
pull_requests:
  do_not_increment_build_number: true
install:
  - git submodule update --init --recursive
  - nuget restore
  - ps: |
        if (-Not $env:APPVEYOR_PULL_REQUEST_TITLE)
        {
            git checkout $env:APPVEYOR_REPO_BRANCH -q
            choco install docfx -y
        }
image: Visual Studio 2017
configuration: Release
platform: x64
cache:
  - '%LocalAppData%\NuGet\v3-cache' # NuGet v3
artifacts:
  - path: IPA/bin/$(configuration)
    name: BSIPA
  - path: BSIPA-ModList/bin/$(configuration)
    name: ModList
build:
  verbosity: normal
  project: BSIPA.sln
skip_tags: true
deploy:
- provider: GitHub
  release: BSIPA $(bsipa_version)-draft
  tag: $(bsipa_version)-d
  description: |
    **Build:** [$(bsipa_version)-$(APPVEYOR_BUILD_NUMBER)](https://ci.appveyor.com/project/nike4613/beatsaber-ipa-reloaded-9smsb/builds/$(APPVEYOR_BUILD_ID)) [$(configuration)|$(platform)]
    **Latest Commit:** $(APPVEYOR_REPO_COMMIT)
    - `$(APPVEYOR_REPO_COMMIT_MESSAGE)`
    - `$(APPVEYOR_REPO_COMMIT_MESSAGE_EXTENDED)`
  auth_token:
    secure: KhF3q/zWEFwrW0QeZLqE3NAkWR4u9iVhsmcyzXvwwJ28fUy+MzW4CWBx3RxNM60t
  artifact: /.*\.zip/
  draft: true
  force_update: true
  on:
    branch: master
after_deploy:
  - ps: |
        if(-Not $env:APPVEYOR_PULL_REQUEST_TITLE -And $env:APPVEYOR_REPO_BRANCH -eq 'master')
        {
            cd IPA.Loader/doc
            & docfx docfx.json
            if ($lastexitcode -ne 0){
              throw [System.Exception] "docfx build failed with exit code $lastexitcode."
            }
            
            git config --global credential.helper store
            Add-Content "$env:USERPROFILE\.git-credentials" "https://$($env:gh_acct_user):$($env:gh_acct_pw)@github.com`n"
            git config --global user.email $env:APPVEYOR_REPO_COMMIT_AUTHOR_EMAIL
            git config --global user.name $env:APPVEYOR_REPO_COMMIT_AUTHOR
            git clone "https://github.com/$($env:APPVEYOR_REPO_NAME).git" -b gh-pages origin_site -q
            Copy-Item origin_site/.git _site -recurse
            CD _site
            git add -A 2>&1
            git commit -m "$env:APPVEYOR_REPO_COMMIT_MESSAGE -- Docs" -q
            git push origin gh-pages -q
        }
